name: 'Swatinem/rust-cache'
description: 'Swatinem/rust-cache with better defaults'
inputs:
  key:
    description: "Swatinem/rust-cache: key"
    required: false
runs:
  using: "composite"
  steps:
    - uses: Swatinem/rust-cache@f13886b937689c021905a6b90929199931d60db1  # v2.8.1
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}  # harden against cache poisoning
      with:
        key: ${{ inputs.key }}
