name: 'Swatinem/rust-cache'
description: 'Swatinem/rust-cache with better defaults'
inputs:
  key:
    description: "Swatinem/rust-cache: key"
    required: false
runs:
  using: "composite"
  steps:
    - uses: Swatinem/rust-cache@98c8021b550208e191a6a3145459bfc9fb29c4c0  # v2.8.0
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}  # harden against cache poisoning
      with:
        key: ${{ inputs.key }}
