version: 2
updates:
  - package-ecosystem: github-actions
    directories: 
     - /
     - checkout/
     - rust-cache/
     - setup-python/
     - setup-uv/
    schedule:
      interval: "monthly"
    groups:
      dependencies:
        patterns:
          - "*"
