name: 'astral-sh/setup-uv'
description: 'astral-sh/setup-uv with better defaults'
runs:
  using: "composite"
  steps:
    - uses: astral-sh/setup-uv@d0cc045d04ccac9d8b7881df0226f9e82c39688e
      with:
        version: "0.8.12"
        enable-cache: ${{ !startsWith(github.ref, 'refs/tags/') }}  # harden against cache poisoning
