name: 'astral-sh/setup-uv'
description: 'astral-sh/setup-uv with better defaults'
runs:
  using: "composite"
  steps:
    - uses: astral-sh/setup-uv@1417e89049849823134e5e847554e76bb77cc550
      with:
        version: "0.7.5"
        enable-cache: ${{ !startsWith(github.ref, 'refs/tags/') }}  # harden against cache poisoning
