name: 'astral-sh/setup-uv'
description: 'astral-sh/setup-uv with better defaults'
runs:
  using: "composite"
  steps:
    - uses: astral-sh/setup-uv@803947b9bd8e9f986429fa0c5a41c367cd732b41
      with:
        version: "0.9.2"
        enable-cache: ${{ !startsWith(github.ref, 'refs/tags/') }}  # harden against cache poisoning
