name: 'astral-sh/setup-uv'
description: 'astral-sh/setup-uv with better defaults'
runs:
  using: "composite"
  steps:
    - uses: astral-sh/setup-uv@d4b2f3b6ecc6e67c4457f6d3e41ec42d3d0fcb86
      with:
        version: "0.6.14"
        enable-cache: ${{ !startsWith(github.ref, 'refs/tags/') }}  # harden against cache poisoning
