name: 'actions/checkout'
description: 'actions/checkout with better defaults'
runs:
  using: "composite"
  steps:
    - run: git config --global core.autocrlf false
      shell: bash
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      with:
        persist-credentials: false
