name: 'uv sync'
description: 'create a venv and add it to $PATH'
inputs:
  args:
    description: "extra arguments for `uv sync`"
runs:
  using: "composite"
  steps:
    - run: uv sync --frozen ${{ inputs.args }}
      shell: bash
    - if: runner.os == 'Windows'
      run: echo "$GITHUB_WORKSPACE\\.venv\\Scripts" >> "$GITHUB_PATH"
      shell: bash
    - if: runner.os != 'Windows'
      run: echo "$GITHUB_WORKSPACE/.venv/bin" >> "$GITHUB_PATH"
      shell: bash
