name: 'actions/setup-python'
description: 'actions/setup-python with better defaults'
inputs:
  python-version:
    description: "actions/setup-python: python-version"
  python-version-file:
    description: "actions/setup-python: python-version-file"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c
      with:
        python-version: ${{ inputs.python-version || (inputs.python-version-file == '' && hashFiles('.github/python-version.txt') == '' && hashFiles('.python-version') == '' && '3.13') || '' }}
        python-version-file: ${{ inputs.python-version-file || (inputs.python-version == '' && hashFiles('.github/python-version.txt') != '' && '.github/python-version.txt') || '' }}
