# Usage:
#
#  build:
#    uses: mhils/workflows/.github/workflows/gh-pages-hugo.yml@main
#    with:
#      deploy: ${{ github.ref == 'refs/heads/main' }}
#    permissions:
#      contents: read
#      id-token: write
#      pages: write

# security: restrict permissions for CI jobs.
permissions:
  contents: read
  
on:
  workflow_call:
    inputs:
      deploy:
        description: 'True if the website should be built and deployed, false if it should be built only.'
        default: true
        required: false
        type: boolean
      working-directory:
        description: 'The hugo base directory.'
        default: "."
        required: false
        type: string

jobs:
  # Build the documentation and upload the static HTML files as an artifact.
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          
      # potentially add https://youtu.be/n39uvwdW5ek?t=579 here.
      
      - run: |
          wget -q https://github.com/gohugoio/hugo/releases/download/v0.142.0/hugo_extended_0.142.0_linux-amd64.deb
          echo "ed20a7c0b74482a3d036c549fd5eaca8c3ea4e74de0bd414193d16503768b44d hugo_extended_0.142.0_linux-amd64.deb" | sha256sum -c
          sudo dpkg -i hugo*.deb
          
      - run: hugo
        working-directory: ${{ inputs.working-directory }}

      - uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ inputs.working-directory }}/public/

  # Deploy the artifact to GitHub pages.
  # This is a separate job so that only actions/deploy-pages has the necessary permissions.
  deploy:
    if: ${{ inputs.deploy }}
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
